PLNT-04195-GDS-Form-Configuration-Service-Secrets-Removed
DEFRA/trade-phes pull request #4
Opened 2021-07-28 15:13 UTC by dav-defra

Remove secrets

2021-07-30 14:10 UTC, imtiaz-defra requested changes

2021-07-30 14:10 UTC, imtiaz-defra commented on plants-form-configuration-service/config.yml
> +    port: 4761
are we exposing something we shouldn't here?

2021-07-30 14:10 UTC, imtiaz-defra commented on .idea/.gitignore
> +# Default ignored files
the `.idea` folder needs to be removed

2021-08-05 08:47 UTC, majikhn approved these changes

2021-08-13 13:53 UTC, imtiaz-defra approved these changes

2021-08-13 13:57 UTC, merged